// Generated by CoffeeScript 1.6.2
"use strict";
var grunt, parser;

grunt = require("grunt");

parser = require("../index");

exports.nodeunit = {
  test_1: function(test) {
    test.expect(1);
    return parser("./test_subjects/chrome_bookmark.html", function(results) {
      console.dir(results);
      test.ok(true, "this had better work.");
      return test.done();
    });
  },
  test_2: function(test) {
    test.expect(1);
    return parser("./test_subjects/chrome_bookmark2.html", function(results) {
      console.dir(results);
      test.ok(true, "this had better work.");
      return test.done();
    });
  }
};
